# Makefile.in generated by automake 1.12.5 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2012 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/xpost
pkgincludedir = $(includedir)/xpost
pkglibdir = $(libdir)/xpost
pkglibexecdir = $(libexecdir)/xpost
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-cygwin
host_triplet = i686-pc-cygwin
bin_PROGRAMS = itp$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	compile config.guess config.sub depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_itp_OBJECTS = itp-ar.$(OBJEXT) itp-di.$(OBJEXT) itp-err.$(OBJEXT) \
	itp-f.$(OBJEXT) itp-gc.$(OBJEXT) itp-itp.$(OBJEXT) \
	itp-m.$(OBJEXT) itp-nm.$(OBJEXT) itp-osunix.$(OBJEXT) \
	itp-s.$(OBJEXT) itp-v.$(OBJEXT) itp-st.$(OBJEXT) \
	itp-ob.$(OBJEXT) itp-op.$(OBJEXT) itp-opar.$(OBJEXT) \
	itp-opb.$(OBJEXT) itp-opc.$(OBJEXT) itp-opdi.$(OBJEXT) \
	itp-opf.$(OBJEXT) itp-opm.$(OBJEXT) itp-oppa.$(OBJEXT) \
	itp-ops.$(OBJEXT) itp-opst.$(OBJEXT) itp-opt.$(OBJEXT) \
	itp-optok.$(OBJEXT) itp-opv.$(OBJEXT) itp-opx.$(OBJEXT)
itp_OBJECTS = $(am_itp_OBJECTS)
itp_LDADD = $(LDADD)
itp_LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(itp_LDFLAGS) $(LDFLAGS) -o \
	$@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(itp_SOURCES)
DIST_SOURCES = $(itp_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
DIST_TARGETS = dist-bzip2 dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/josh/xpost/missing --run aclocal-1.12
ALLOCA = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AUTOCONF = ${SHELL} /home/josh/xpost/missing --run autoconf
AUTOHEADER = ${SHELL} /home/josh/xpost/missing --run autoheader
AUTOMAKE = ${SHELL} /home/josh/xpost/missing --run automake-1.12
AWK = gawk
CC = gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -std=gnu99 -E
CPPFLAGS = 
CYGPATH_W = cygpath -w
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = .exe
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/josh/xpost/missing --run makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = xpost
PACKAGE_BUGREPORT = luser.droog.remove@gmail.com
PACKAGE_NAME = xpost
PACKAGE_STRING = xpost 0.0.2
PACKAGE_TARNAME = xpost
PACKAGE_URL = 
PACKAGE_VERSION = 0.0.2
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 0.0.2
abs_builddir = /home/josh/xpost
abs_srcdir = /home/josh/xpost
abs_top_builddir = /home/josh/xpost
abs_top_srcdir = /home/josh/xpost
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-cygwin
build_alias = 
build_cpu = i686
build_os = cygwin
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-cygwin
host_alias = 
host_cpu = i686
host_os = cygwin
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/josh/xpost/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
MAINTAINERCLEANFILES = \
Makefile.in \
compile \
config.guess \
config.h.in \
config.h.in~ \
config.sub \
configure \
depcomp \
install-sh \
missing

itp_SOURCES = \
ar.c \
di.c \
err.c \
f.c \
gc.c \
itp.c \
m.c \
nm.c \
osunix.c \
s.c \
v.c \
st.c \
ob.c \
op.c \
opar.c \
opb.c \
opc.c \
opdi.c \
opf.c \
opm.c \
oppa.c \
ops.c \
opst.c \
opt.c \
optok.c \
opv.c \
opx.c

itp_CPPFLAGS = -DTESTMODULE_ITP
itp_LDFLAGS = -lm
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
itp$(EXEEXT): $(itp_OBJECTS) $(itp_DEPENDENCIES) $(EXTRA_itp_DEPENDENCIES) 
	@rm -f itp$(EXEEXT)
	$(AM_V_CCLD)$(itp_LINK) $(itp_OBJECTS) $(itp_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/itp-ar.Po
include ./$(DEPDIR)/itp-di.Po
include ./$(DEPDIR)/itp-err.Po
include ./$(DEPDIR)/itp-f.Po
include ./$(DEPDIR)/itp-gc.Po
include ./$(DEPDIR)/itp-itp.Po
include ./$(DEPDIR)/itp-m.Po
include ./$(DEPDIR)/itp-nm.Po
include ./$(DEPDIR)/itp-ob.Po
include ./$(DEPDIR)/itp-op.Po
include ./$(DEPDIR)/itp-opar.Po
include ./$(DEPDIR)/itp-opb.Po
include ./$(DEPDIR)/itp-opc.Po
include ./$(DEPDIR)/itp-opdi.Po
include ./$(DEPDIR)/itp-opf.Po
include ./$(DEPDIR)/itp-opm.Po
include ./$(DEPDIR)/itp-oppa.Po
include ./$(DEPDIR)/itp-ops.Po
include ./$(DEPDIR)/itp-opst.Po
include ./$(DEPDIR)/itp-opt.Po
include ./$(DEPDIR)/itp-optok.Po
include ./$(DEPDIR)/itp-opv.Po
include ./$(DEPDIR)/itp-opx.Po
include ./$(DEPDIR)/itp-osunix.Po
include ./$(DEPDIR)/itp-s.Po
include ./$(DEPDIR)/itp-st.Po
include ./$(DEPDIR)/itp-v.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c `$(CYGPATH_W) '$<'`

itp-ar.o: ar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-ar.o -MD -MP -MF $(DEPDIR)/itp-ar.Tpo -c -o itp-ar.o `test -f 'ar.c' || echo '$(srcdir)/'`ar.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-ar.Tpo $(DEPDIR)/itp-ar.Po
#	$(AM_V_CC)source='ar.c' object='itp-ar.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-ar.o `test -f 'ar.c' || echo '$(srcdir)/'`ar.c

itp-ar.obj: ar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-ar.obj -MD -MP -MF $(DEPDIR)/itp-ar.Tpo -c -o itp-ar.obj `if test -f 'ar.c'; then $(CYGPATH_W) 'ar.c'; else $(CYGPATH_W) '$(srcdir)/ar.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-ar.Tpo $(DEPDIR)/itp-ar.Po
#	$(AM_V_CC)source='ar.c' object='itp-ar.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-ar.obj `if test -f 'ar.c'; then $(CYGPATH_W) 'ar.c'; else $(CYGPATH_W) '$(srcdir)/ar.c'; fi`

itp-di.o: di.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-di.o -MD -MP -MF $(DEPDIR)/itp-di.Tpo -c -o itp-di.o `test -f 'di.c' || echo '$(srcdir)/'`di.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-di.Tpo $(DEPDIR)/itp-di.Po
#	$(AM_V_CC)source='di.c' object='itp-di.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-di.o `test -f 'di.c' || echo '$(srcdir)/'`di.c

itp-di.obj: di.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-di.obj -MD -MP -MF $(DEPDIR)/itp-di.Tpo -c -o itp-di.obj `if test -f 'di.c'; then $(CYGPATH_W) 'di.c'; else $(CYGPATH_W) '$(srcdir)/di.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-di.Tpo $(DEPDIR)/itp-di.Po
#	$(AM_V_CC)source='di.c' object='itp-di.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-di.obj `if test -f 'di.c'; then $(CYGPATH_W) 'di.c'; else $(CYGPATH_W) '$(srcdir)/di.c'; fi`

itp-err.o: err.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-err.o -MD -MP -MF $(DEPDIR)/itp-err.Tpo -c -o itp-err.o `test -f 'err.c' || echo '$(srcdir)/'`err.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-err.Tpo $(DEPDIR)/itp-err.Po
#	$(AM_V_CC)source='err.c' object='itp-err.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-err.o `test -f 'err.c' || echo '$(srcdir)/'`err.c

itp-err.obj: err.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-err.obj -MD -MP -MF $(DEPDIR)/itp-err.Tpo -c -o itp-err.obj `if test -f 'err.c'; then $(CYGPATH_W) 'err.c'; else $(CYGPATH_W) '$(srcdir)/err.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-err.Tpo $(DEPDIR)/itp-err.Po
#	$(AM_V_CC)source='err.c' object='itp-err.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-err.obj `if test -f 'err.c'; then $(CYGPATH_W) 'err.c'; else $(CYGPATH_W) '$(srcdir)/err.c'; fi`

itp-f.o: f.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-f.o -MD -MP -MF $(DEPDIR)/itp-f.Tpo -c -o itp-f.o `test -f 'f.c' || echo '$(srcdir)/'`f.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-f.Tpo $(DEPDIR)/itp-f.Po
#	$(AM_V_CC)source='f.c' object='itp-f.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-f.o `test -f 'f.c' || echo '$(srcdir)/'`f.c

itp-f.obj: f.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-f.obj -MD -MP -MF $(DEPDIR)/itp-f.Tpo -c -o itp-f.obj `if test -f 'f.c'; then $(CYGPATH_W) 'f.c'; else $(CYGPATH_W) '$(srcdir)/f.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-f.Tpo $(DEPDIR)/itp-f.Po
#	$(AM_V_CC)source='f.c' object='itp-f.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-f.obj `if test -f 'f.c'; then $(CYGPATH_W) 'f.c'; else $(CYGPATH_W) '$(srcdir)/f.c'; fi`

itp-gc.o: gc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-gc.o -MD -MP -MF $(DEPDIR)/itp-gc.Tpo -c -o itp-gc.o `test -f 'gc.c' || echo '$(srcdir)/'`gc.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-gc.Tpo $(DEPDIR)/itp-gc.Po
#	$(AM_V_CC)source='gc.c' object='itp-gc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-gc.o `test -f 'gc.c' || echo '$(srcdir)/'`gc.c

itp-gc.obj: gc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-gc.obj -MD -MP -MF $(DEPDIR)/itp-gc.Tpo -c -o itp-gc.obj `if test -f 'gc.c'; then $(CYGPATH_W) 'gc.c'; else $(CYGPATH_W) '$(srcdir)/gc.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-gc.Tpo $(DEPDIR)/itp-gc.Po
#	$(AM_V_CC)source='gc.c' object='itp-gc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-gc.obj `if test -f 'gc.c'; then $(CYGPATH_W) 'gc.c'; else $(CYGPATH_W) '$(srcdir)/gc.c'; fi`

itp-itp.o: itp.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-itp.o -MD -MP -MF $(DEPDIR)/itp-itp.Tpo -c -o itp-itp.o `test -f 'itp.c' || echo '$(srcdir)/'`itp.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-itp.Tpo $(DEPDIR)/itp-itp.Po
#	$(AM_V_CC)source='itp.c' object='itp-itp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-itp.o `test -f 'itp.c' || echo '$(srcdir)/'`itp.c

itp-itp.obj: itp.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-itp.obj -MD -MP -MF $(DEPDIR)/itp-itp.Tpo -c -o itp-itp.obj `if test -f 'itp.c'; then $(CYGPATH_W) 'itp.c'; else $(CYGPATH_W) '$(srcdir)/itp.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-itp.Tpo $(DEPDIR)/itp-itp.Po
#	$(AM_V_CC)source='itp.c' object='itp-itp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-itp.obj `if test -f 'itp.c'; then $(CYGPATH_W) 'itp.c'; else $(CYGPATH_W) '$(srcdir)/itp.c'; fi`

itp-m.o: m.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-m.o -MD -MP -MF $(DEPDIR)/itp-m.Tpo -c -o itp-m.o `test -f 'm.c' || echo '$(srcdir)/'`m.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-m.Tpo $(DEPDIR)/itp-m.Po
#	$(AM_V_CC)source='m.c' object='itp-m.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-m.o `test -f 'm.c' || echo '$(srcdir)/'`m.c

itp-m.obj: m.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-m.obj -MD -MP -MF $(DEPDIR)/itp-m.Tpo -c -o itp-m.obj `if test -f 'm.c'; then $(CYGPATH_W) 'm.c'; else $(CYGPATH_W) '$(srcdir)/m.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-m.Tpo $(DEPDIR)/itp-m.Po
#	$(AM_V_CC)source='m.c' object='itp-m.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-m.obj `if test -f 'm.c'; then $(CYGPATH_W) 'm.c'; else $(CYGPATH_W) '$(srcdir)/m.c'; fi`

itp-nm.o: nm.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-nm.o -MD -MP -MF $(DEPDIR)/itp-nm.Tpo -c -o itp-nm.o `test -f 'nm.c' || echo '$(srcdir)/'`nm.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-nm.Tpo $(DEPDIR)/itp-nm.Po
#	$(AM_V_CC)source='nm.c' object='itp-nm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-nm.o `test -f 'nm.c' || echo '$(srcdir)/'`nm.c

itp-nm.obj: nm.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-nm.obj -MD -MP -MF $(DEPDIR)/itp-nm.Tpo -c -o itp-nm.obj `if test -f 'nm.c'; then $(CYGPATH_W) 'nm.c'; else $(CYGPATH_W) '$(srcdir)/nm.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-nm.Tpo $(DEPDIR)/itp-nm.Po
#	$(AM_V_CC)source='nm.c' object='itp-nm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-nm.obj `if test -f 'nm.c'; then $(CYGPATH_W) 'nm.c'; else $(CYGPATH_W) '$(srcdir)/nm.c'; fi`

itp-osunix.o: osunix.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-osunix.o -MD -MP -MF $(DEPDIR)/itp-osunix.Tpo -c -o itp-osunix.o `test -f 'osunix.c' || echo '$(srcdir)/'`osunix.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-osunix.Tpo $(DEPDIR)/itp-osunix.Po
#	$(AM_V_CC)source='osunix.c' object='itp-osunix.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-osunix.o `test -f 'osunix.c' || echo '$(srcdir)/'`osunix.c

itp-osunix.obj: osunix.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-osunix.obj -MD -MP -MF $(DEPDIR)/itp-osunix.Tpo -c -o itp-osunix.obj `if test -f 'osunix.c'; then $(CYGPATH_W) 'osunix.c'; else $(CYGPATH_W) '$(srcdir)/osunix.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-osunix.Tpo $(DEPDIR)/itp-osunix.Po
#	$(AM_V_CC)source='osunix.c' object='itp-osunix.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-osunix.obj `if test -f 'osunix.c'; then $(CYGPATH_W) 'osunix.c'; else $(CYGPATH_W) '$(srcdir)/osunix.c'; fi`

itp-s.o: s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-s.o -MD -MP -MF $(DEPDIR)/itp-s.Tpo -c -o itp-s.o `test -f 's.c' || echo '$(srcdir)/'`s.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-s.Tpo $(DEPDIR)/itp-s.Po
#	$(AM_V_CC)source='s.c' object='itp-s.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-s.o `test -f 's.c' || echo '$(srcdir)/'`s.c

itp-s.obj: s.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-s.obj -MD -MP -MF $(DEPDIR)/itp-s.Tpo -c -o itp-s.obj `if test -f 's.c'; then $(CYGPATH_W) 's.c'; else $(CYGPATH_W) '$(srcdir)/s.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-s.Tpo $(DEPDIR)/itp-s.Po
#	$(AM_V_CC)source='s.c' object='itp-s.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-s.obj `if test -f 's.c'; then $(CYGPATH_W) 's.c'; else $(CYGPATH_W) '$(srcdir)/s.c'; fi`

itp-v.o: v.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-v.o -MD -MP -MF $(DEPDIR)/itp-v.Tpo -c -o itp-v.o `test -f 'v.c' || echo '$(srcdir)/'`v.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-v.Tpo $(DEPDIR)/itp-v.Po
#	$(AM_V_CC)source='v.c' object='itp-v.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-v.o `test -f 'v.c' || echo '$(srcdir)/'`v.c

itp-v.obj: v.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-v.obj -MD -MP -MF $(DEPDIR)/itp-v.Tpo -c -o itp-v.obj `if test -f 'v.c'; then $(CYGPATH_W) 'v.c'; else $(CYGPATH_W) '$(srcdir)/v.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-v.Tpo $(DEPDIR)/itp-v.Po
#	$(AM_V_CC)source='v.c' object='itp-v.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-v.obj `if test -f 'v.c'; then $(CYGPATH_W) 'v.c'; else $(CYGPATH_W) '$(srcdir)/v.c'; fi`

itp-st.o: st.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-st.o -MD -MP -MF $(DEPDIR)/itp-st.Tpo -c -o itp-st.o `test -f 'st.c' || echo '$(srcdir)/'`st.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-st.Tpo $(DEPDIR)/itp-st.Po
#	$(AM_V_CC)source='st.c' object='itp-st.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-st.o `test -f 'st.c' || echo '$(srcdir)/'`st.c

itp-st.obj: st.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-st.obj -MD -MP -MF $(DEPDIR)/itp-st.Tpo -c -o itp-st.obj `if test -f 'st.c'; then $(CYGPATH_W) 'st.c'; else $(CYGPATH_W) '$(srcdir)/st.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-st.Tpo $(DEPDIR)/itp-st.Po
#	$(AM_V_CC)source='st.c' object='itp-st.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-st.obj `if test -f 'st.c'; then $(CYGPATH_W) 'st.c'; else $(CYGPATH_W) '$(srcdir)/st.c'; fi`

itp-ob.o: ob.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-ob.o -MD -MP -MF $(DEPDIR)/itp-ob.Tpo -c -o itp-ob.o `test -f 'ob.c' || echo '$(srcdir)/'`ob.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-ob.Tpo $(DEPDIR)/itp-ob.Po
#	$(AM_V_CC)source='ob.c' object='itp-ob.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-ob.o `test -f 'ob.c' || echo '$(srcdir)/'`ob.c

itp-ob.obj: ob.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-ob.obj -MD -MP -MF $(DEPDIR)/itp-ob.Tpo -c -o itp-ob.obj `if test -f 'ob.c'; then $(CYGPATH_W) 'ob.c'; else $(CYGPATH_W) '$(srcdir)/ob.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-ob.Tpo $(DEPDIR)/itp-ob.Po
#	$(AM_V_CC)source='ob.c' object='itp-ob.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-ob.obj `if test -f 'ob.c'; then $(CYGPATH_W) 'ob.c'; else $(CYGPATH_W) '$(srcdir)/ob.c'; fi`

itp-op.o: op.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-op.o -MD -MP -MF $(DEPDIR)/itp-op.Tpo -c -o itp-op.o `test -f 'op.c' || echo '$(srcdir)/'`op.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-op.Tpo $(DEPDIR)/itp-op.Po
#	$(AM_V_CC)source='op.c' object='itp-op.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-op.o `test -f 'op.c' || echo '$(srcdir)/'`op.c

itp-op.obj: op.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-op.obj -MD -MP -MF $(DEPDIR)/itp-op.Tpo -c -o itp-op.obj `if test -f 'op.c'; then $(CYGPATH_W) 'op.c'; else $(CYGPATH_W) '$(srcdir)/op.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-op.Tpo $(DEPDIR)/itp-op.Po
#	$(AM_V_CC)source='op.c' object='itp-op.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-op.obj `if test -f 'op.c'; then $(CYGPATH_W) 'op.c'; else $(CYGPATH_W) '$(srcdir)/op.c'; fi`

itp-opar.o: opar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opar.o -MD -MP -MF $(DEPDIR)/itp-opar.Tpo -c -o itp-opar.o `test -f 'opar.c' || echo '$(srcdir)/'`opar.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opar.Tpo $(DEPDIR)/itp-opar.Po
#	$(AM_V_CC)source='opar.c' object='itp-opar.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opar.o `test -f 'opar.c' || echo '$(srcdir)/'`opar.c

itp-opar.obj: opar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opar.obj -MD -MP -MF $(DEPDIR)/itp-opar.Tpo -c -o itp-opar.obj `if test -f 'opar.c'; then $(CYGPATH_W) 'opar.c'; else $(CYGPATH_W) '$(srcdir)/opar.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opar.Tpo $(DEPDIR)/itp-opar.Po
#	$(AM_V_CC)source='opar.c' object='itp-opar.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opar.obj `if test -f 'opar.c'; then $(CYGPATH_W) 'opar.c'; else $(CYGPATH_W) '$(srcdir)/opar.c'; fi`

itp-opb.o: opb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opb.o -MD -MP -MF $(DEPDIR)/itp-opb.Tpo -c -o itp-opb.o `test -f 'opb.c' || echo '$(srcdir)/'`opb.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opb.Tpo $(DEPDIR)/itp-opb.Po
#	$(AM_V_CC)source='opb.c' object='itp-opb.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opb.o `test -f 'opb.c' || echo '$(srcdir)/'`opb.c

itp-opb.obj: opb.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opb.obj -MD -MP -MF $(DEPDIR)/itp-opb.Tpo -c -o itp-opb.obj `if test -f 'opb.c'; then $(CYGPATH_W) 'opb.c'; else $(CYGPATH_W) '$(srcdir)/opb.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opb.Tpo $(DEPDIR)/itp-opb.Po
#	$(AM_V_CC)source='opb.c' object='itp-opb.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opb.obj `if test -f 'opb.c'; then $(CYGPATH_W) 'opb.c'; else $(CYGPATH_W) '$(srcdir)/opb.c'; fi`

itp-opc.o: opc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opc.o -MD -MP -MF $(DEPDIR)/itp-opc.Tpo -c -o itp-opc.o `test -f 'opc.c' || echo '$(srcdir)/'`opc.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opc.Tpo $(DEPDIR)/itp-opc.Po
#	$(AM_V_CC)source='opc.c' object='itp-opc.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opc.o `test -f 'opc.c' || echo '$(srcdir)/'`opc.c

itp-opc.obj: opc.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opc.obj -MD -MP -MF $(DEPDIR)/itp-opc.Tpo -c -o itp-opc.obj `if test -f 'opc.c'; then $(CYGPATH_W) 'opc.c'; else $(CYGPATH_W) '$(srcdir)/opc.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opc.Tpo $(DEPDIR)/itp-opc.Po
#	$(AM_V_CC)source='opc.c' object='itp-opc.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opc.obj `if test -f 'opc.c'; then $(CYGPATH_W) 'opc.c'; else $(CYGPATH_W) '$(srcdir)/opc.c'; fi`

itp-opdi.o: opdi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opdi.o -MD -MP -MF $(DEPDIR)/itp-opdi.Tpo -c -o itp-opdi.o `test -f 'opdi.c' || echo '$(srcdir)/'`opdi.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opdi.Tpo $(DEPDIR)/itp-opdi.Po
#	$(AM_V_CC)source='opdi.c' object='itp-opdi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opdi.o `test -f 'opdi.c' || echo '$(srcdir)/'`opdi.c

itp-opdi.obj: opdi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opdi.obj -MD -MP -MF $(DEPDIR)/itp-opdi.Tpo -c -o itp-opdi.obj `if test -f 'opdi.c'; then $(CYGPATH_W) 'opdi.c'; else $(CYGPATH_W) '$(srcdir)/opdi.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opdi.Tpo $(DEPDIR)/itp-opdi.Po
#	$(AM_V_CC)source='opdi.c' object='itp-opdi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opdi.obj `if test -f 'opdi.c'; then $(CYGPATH_W) 'opdi.c'; else $(CYGPATH_W) '$(srcdir)/opdi.c'; fi`

itp-opf.o: opf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opf.o -MD -MP -MF $(DEPDIR)/itp-opf.Tpo -c -o itp-opf.o `test -f 'opf.c' || echo '$(srcdir)/'`opf.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opf.Tpo $(DEPDIR)/itp-opf.Po
#	$(AM_V_CC)source='opf.c' object='itp-opf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opf.o `test -f 'opf.c' || echo '$(srcdir)/'`opf.c

itp-opf.obj: opf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opf.obj -MD -MP -MF $(DEPDIR)/itp-opf.Tpo -c -o itp-opf.obj `if test -f 'opf.c'; then $(CYGPATH_W) 'opf.c'; else $(CYGPATH_W) '$(srcdir)/opf.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opf.Tpo $(DEPDIR)/itp-opf.Po
#	$(AM_V_CC)source='opf.c' object='itp-opf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opf.obj `if test -f 'opf.c'; then $(CYGPATH_W) 'opf.c'; else $(CYGPATH_W) '$(srcdir)/opf.c'; fi`

itp-opm.o: opm.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opm.o -MD -MP -MF $(DEPDIR)/itp-opm.Tpo -c -o itp-opm.o `test -f 'opm.c' || echo '$(srcdir)/'`opm.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opm.Tpo $(DEPDIR)/itp-opm.Po
#	$(AM_V_CC)source='opm.c' object='itp-opm.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opm.o `test -f 'opm.c' || echo '$(srcdir)/'`opm.c

itp-opm.obj: opm.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opm.obj -MD -MP -MF $(DEPDIR)/itp-opm.Tpo -c -o itp-opm.obj `if test -f 'opm.c'; then $(CYGPATH_W) 'opm.c'; else $(CYGPATH_W) '$(srcdir)/opm.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opm.Tpo $(DEPDIR)/itp-opm.Po
#	$(AM_V_CC)source='opm.c' object='itp-opm.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opm.obj `if test -f 'opm.c'; then $(CYGPATH_W) 'opm.c'; else $(CYGPATH_W) '$(srcdir)/opm.c'; fi`

itp-oppa.o: oppa.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-oppa.o -MD -MP -MF $(DEPDIR)/itp-oppa.Tpo -c -o itp-oppa.o `test -f 'oppa.c' || echo '$(srcdir)/'`oppa.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-oppa.Tpo $(DEPDIR)/itp-oppa.Po
#	$(AM_V_CC)source='oppa.c' object='itp-oppa.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-oppa.o `test -f 'oppa.c' || echo '$(srcdir)/'`oppa.c

itp-oppa.obj: oppa.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-oppa.obj -MD -MP -MF $(DEPDIR)/itp-oppa.Tpo -c -o itp-oppa.obj `if test -f 'oppa.c'; then $(CYGPATH_W) 'oppa.c'; else $(CYGPATH_W) '$(srcdir)/oppa.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-oppa.Tpo $(DEPDIR)/itp-oppa.Po
#	$(AM_V_CC)source='oppa.c' object='itp-oppa.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-oppa.obj `if test -f 'oppa.c'; then $(CYGPATH_W) 'oppa.c'; else $(CYGPATH_W) '$(srcdir)/oppa.c'; fi`

itp-ops.o: ops.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-ops.o -MD -MP -MF $(DEPDIR)/itp-ops.Tpo -c -o itp-ops.o `test -f 'ops.c' || echo '$(srcdir)/'`ops.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-ops.Tpo $(DEPDIR)/itp-ops.Po
#	$(AM_V_CC)source='ops.c' object='itp-ops.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-ops.o `test -f 'ops.c' || echo '$(srcdir)/'`ops.c

itp-ops.obj: ops.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-ops.obj -MD -MP -MF $(DEPDIR)/itp-ops.Tpo -c -o itp-ops.obj `if test -f 'ops.c'; then $(CYGPATH_W) 'ops.c'; else $(CYGPATH_W) '$(srcdir)/ops.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-ops.Tpo $(DEPDIR)/itp-ops.Po
#	$(AM_V_CC)source='ops.c' object='itp-ops.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-ops.obj `if test -f 'ops.c'; then $(CYGPATH_W) 'ops.c'; else $(CYGPATH_W) '$(srcdir)/ops.c'; fi`

itp-opst.o: opst.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opst.o -MD -MP -MF $(DEPDIR)/itp-opst.Tpo -c -o itp-opst.o `test -f 'opst.c' || echo '$(srcdir)/'`opst.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opst.Tpo $(DEPDIR)/itp-opst.Po
#	$(AM_V_CC)source='opst.c' object='itp-opst.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opst.o `test -f 'opst.c' || echo '$(srcdir)/'`opst.c

itp-opst.obj: opst.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opst.obj -MD -MP -MF $(DEPDIR)/itp-opst.Tpo -c -o itp-opst.obj `if test -f 'opst.c'; then $(CYGPATH_W) 'opst.c'; else $(CYGPATH_W) '$(srcdir)/opst.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opst.Tpo $(DEPDIR)/itp-opst.Po
#	$(AM_V_CC)source='opst.c' object='itp-opst.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opst.obj `if test -f 'opst.c'; then $(CYGPATH_W) 'opst.c'; else $(CYGPATH_W) '$(srcdir)/opst.c'; fi`

itp-opt.o: opt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opt.o -MD -MP -MF $(DEPDIR)/itp-opt.Tpo -c -o itp-opt.o `test -f 'opt.c' || echo '$(srcdir)/'`opt.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opt.Tpo $(DEPDIR)/itp-opt.Po
#	$(AM_V_CC)source='opt.c' object='itp-opt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opt.o `test -f 'opt.c' || echo '$(srcdir)/'`opt.c

itp-opt.obj: opt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opt.obj -MD -MP -MF $(DEPDIR)/itp-opt.Tpo -c -o itp-opt.obj `if test -f 'opt.c'; then $(CYGPATH_W) 'opt.c'; else $(CYGPATH_W) '$(srcdir)/opt.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opt.Tpo $(DEPDIR)/itp-opt.Po
#	$(AM_V_CC)source='opt.c' object='itp-opt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opt.obj `if test -f 'opt.c'; then $(CYGPATH_W) 'opt.c'; else $(CYGPATH_W) '$(srcdir)/opt.c'; fi`

itp-optok.o: optok.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-optok.o -MD -MP -MF $(DEPDIR)/itp-optok.Tpo -c -o itp-optok.o `test -f 'optok.c' || echo '$(srcdir)/'`optok.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-optok.Tpo $(DEPDIR)/itp-optok.Po
#	$(AM_V_CC)source='optok.c' object='itp-optok.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-optok.o `test -f 'optok.c' || echo '$(srcdir)/'`optok.c

itp-optok.obj: optok.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-optok.obj -MD -MP -MF $(DEPDIR)/itp-optok.Tpo -c -o itp-optok.obj `if test -f 'optok.c'; then $(CYGPATH_W) 'optok.c'; else $(CYGPATH_W) '$(srcdir)/optok.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-optok.Tpo $(DEPDIR)/itp-optok.Po
#	$(AM_V_CC)source='optok.c' object='itp-optok.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-optok.obj `if test -f 'optok.c'; then $(CYGPATH_W) 'optok.c'; else $(CYGPATH_W) '$(srcdir)/optok.c'; fi`

itp-opv.o: opv.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opv.o -MD -MP -MF $(DEPDIR)/itp-opv.Tpo -c -o itp-opv.o `test -f 'opv.c' || echo '$(srcdir)/'`opv.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opv.Tpo $(DEPDIR)/itp-opv.Po
#	$(AM_V_CC)source='opv.c' object='itp-opv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opv.o `test -f 'opv.c' || echo '$(srcdir)/'`opv.c

itp-opv.obj: opv.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opv.obj -MD -MP -MF $(DEPDIR)/itp-opv.Tpo -c -o itp-opv.obj `if test -f 'opv.c'; then $(CYGPATH_W) 'opv.c'; else $(CYGPATH_W) '$(srcdir)/opv.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opv.Tpo $(DEPDIR)/itp-opv.Po
#	$(AM_V_CC)source='opv.c' object='itp-opv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opv.obj `if test -f 'opv.c'; then $(CYGPATH_W) 'opv.c'; else $(CYGPATH_W) '$(srcdir)/opv.c'; fi`

itp-opx.o: opx.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opx.o -MD -MP -MF $(DEPDIR)/itp-opx.Tpo -c -o itp-opx.o `test -f 'opx.c' || echo '$(srcdir)/'`opx.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opx.Tpo $(DEPDIR)/itp-opx.Po
#	$(AM_V_CC)source='opx.c' object='itp-opx.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opx.o `test -f 'opx.c' || echo '$(srcdir)/'`opx.c

itp-opx.obj: opx.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT itp-opx.obj -MD -MP -MF $(DEPDIR)/itp-opx.Tpo -c -o itp-opx.obj `if test -f 'opx.c'; then $(CYGPATH_W) 'opx.c'; else $(CYGPATH_W) '$(srcdir)/opx.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/itp-opx.Tpo $(DEPDIR)/itp-opx.Po
#	$(AM_V_CC)source='opx.c' object='itp-opx.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(itp_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o itp-opx.obj `if test -f 'opx.c'; then $(CYGPATH_W) 'opx.c'; else $(CYGPATH_W) '$(srcdir)/opx.c'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)

clean-cscope:
	-rm -f cscope.files

cscope.files: clean-cscope  cscopelist

cscopelist:  $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS) $(LISP)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope cscopelist \
	ctags dist dist-all dist-bzip2 dist-gzip dist-lzip dist-shar \
	dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
