name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt install build-essential libpng-dev libjpeg-dev libfreetype6-dev libfontconfig1-dev libxcb-icccm4-dev libxcb-image0-dev libxcb1-dev libxcb-util-dev check
    - name: configure
      run: autoreconf -vif && ./configure --with-tests=regular
    - name: make
      run: make V=1
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
