name: msys2

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  test:
    strategy:
      matrix:
        config:
          - msystem: mingw32
            install: base-devel git mingw-w64-i686-toolchain mingw-w64-i686-autotools mingw-w64-i686-libjpeg-turbo mingw-w64-i686-libpng mingw-w64-i686-freetype mingw-w64-i686-fontconfig mingw-w64-i686-check
          - msystem: mingw64
            install: base-devel git  mingw-w64-x86_64-toolchain mingw-w64-x86_64-autotools mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng mingw-w64-x86_64-freetype mingw-w64-x86_64-fontconfig mingw-w64-x86_64-check
    name: msys2 - ${{ matrix.config.msystem }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@master
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.config.msystem }}
        update: true
        install: ${{ matrix.config.install }}
    - name: configure
      run: autoreconf -vif && ./configure --with-tests=regular
    - name: configure
      run: make V=1
    - name: test
      run: make check
